name: gnome-twitch
version: '0.4.1'
summary: Enjoy Twitch on your GNU/Linux desktop
description: |
  Enjoy Twitch on your GNU/Linux desktop
  .
  Easily browse and search channels and games. Keep track of your follows
  whether you have a Twitch account or not.
  A super fast, hardware-accelerated player plus a fully integrated native
  chat makes for a fantastic viewing experience.
  GNOME Twitch is packed with cool features and development is constantly
  on-going, bringing heaps of new stuff straight to you.
icon: data/icons/com.vinszent.GnomeTwitch.svg

grade: devel
confinement: strict

slots:
  dbus-gnome-twitch:
    interface: dbus
    bus: session
    name: com.vinszent.GnomeTwitch

plugs:
  gnome-3-24-platform:
    interface: content
    target: gnome-platform
    default-provider: gnome-3-24:gnome-3-24-platform

apps:
  gnome-twitch:
    command: |
      desktop-launch libopenh264-launch pulse-launch gstreamer-launch ${SNAP}/usr/bin/gnome-twitch
    plugs:
      - gnome-3-24-platform
      - gsettings
      - network
      - opengl
      - pulseaudio
      - unity7
      - x11

parts:
  prepare:
    plugin: nil
    prepare: |
      echo "deb http://ppa.launchpad.net/ubuntu-desktop/gnome-3-24/ubuntu xenial main" | tee /etc/apt/sources.list.d/gnome-3-24.list
      apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 399B698EEA9EF163B6F9A0F62CC98497A1231595
      apt update
      apt upgrade -yy

  gstreamer-launch:
    plugin: dump
    source: snap-files
    prepare: |
      chmod +x gstreamer-launch
      chmod +x pulse-launch
    organize:
      gstreamer-launch: bin/gstreamer-launch
      pulse-launch: bin/pulse-launch

  libopenh264-helper:
    source: libopenh264-helper
    source-subdir: libopenh264
    plugin: make
    stage-packages:
      - bzip2
      - curl
    after: [libopenh264-library]
    prime:
      - -bin/bz*
      - -etc
      - -usr/lib/gcc
      - -usr/lib/sasl2
      - -usr/share

  libopenh264-library:
    plugin: make
    source: https://github.com/cisco/openh264/archive/v1.7.0.tar.gz
    build-packages:
      - g++
      - libasound2-dev
      - libpulse-dev
      - nasm
    stage-packages: [libpulse0]
    prime:
      - -usr/local/include
      - -usr/local/lib/pkgconfig

  gstreamer:
    plugin: autotools
    source: http://gstreamer.freedesktop.org/src/gstreamer/gstreamer-1.10.4.tar.xz
    configflags:
      - --prefix=/usr
      - --disable-rpath
      - --disable-gst-debug
      - --disable-gst-tracer-hooks
      - --disable-debug
      - --disable-examples
      - --disable-tests
      - --disable-benchmarks
      - --disable-tools
      - --disable-check
    build-packages:
      - bison
      - flex
      - libasound2-dev
      - liborc-0.4-dev
    stage-packages:
      - liborc-0.4-0
    after: [libopenh264-library, prepare]
    prime:
      - -usr/bin
      - -usr/include
      - -usr/lib/gcc
      - -usr/lib/pkgconfig
      - -usr/libexec/gstreamer-1.0/gst-ptp-helper
      - -usr/share/aclocal
      - -usr/share/bash-completion
      - -usr/share/doc
      - -usr/share/gtk-doc
    build-attributes: [no-system-libraries]

  gst-plugins-base:
    plugin: autotools
    source: http://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-1.10.4.tar.xz
    configflags:
      - --prefix=/usr
    build-packages: [libasound2-dev, libcairo2-dev, libpulse-dev]
    stage-packages: [libpulse0]
    after: [gstreamer, prepare]
    prime:
      - -usr/bin
      - -usr/include
      - -usr/lib/pkgconfig
      - -usr/share/gst-plugins-base
      - -usr/share/gtk-doc
      - -usr/share/man
    build-attributes: [no-system-libraries]

  gst-plugins-libav:
    plugin: autotools
    source: http://gstreamer.freedesktop.org/src/gst-libav/gst-libav-1.10.4.tar.xz
    configflags:
      - --prefix=/usr
      - --enable-small
      - --disable-programs
      - --disable-doc
      - --disable-w32threads
      - --disable-os2threads
      - --disable-encoders
      - --disable-indevs
      - --enable-gnutls
    build-packages:
      - bison
      - flex
      - libasound2-dev
      - libgnutls28-dev
      - liborc-0.4-dev
      - libpulse-dev
      - yasm
    stage-packages:
      - libgnutls30
      - liborc-0.4-0
      - libpulse0
    after: [gstreamer, gst-plugins-base, libopenh264-library, prepare]
    prime:
      - -usr/lib/gcc
      - -usr/share/doc
      - -usr/share/gtk-doc
    build-attributes: [no-system-libraries]

  gst-plugins-good:
    plugin: autotools
    source: http://gstreamer.freedesktop.org/src/gst-plugins-good/gst-plugins-good-1.10.4.tar.xz
    configflags:
      - --prefix=/usr
      - --disable-rpath
      - --disable-debug
      - --disable-examples
      - --disable-alpha
      - --disable-apetag
      - --disable-audiofx
      - --disable-cutter
      - --disable-debugutils
      - --disable-dtmf
      - --disable-effectv
      - --disable-equalizer
      - --disable-flv
      - --disable-flx
      - --disable-goom
      - --disable-goom2k1
      - --disable-icydemux
      - --disable-id3demux
      - --disable-imagefreeze
      - --disable-interleave
      - --disable-law
      - --disable-level
      - --disable-monoscope
      - --disable-replaygain
      - --disable-rtp
      - --disable-rtpmanager
      - --disable-rtsp
      - --disable-shapewipe
      - --disable-smpte
      - --disable-spectrum
      - --disable-udp
      - --disable-videobox
      - --disable-wavenc
      - --disable-wavparse
      - --disable-y4m
      - --disable-directsound
      - --disable-waveform
      - --disable-oss
      - --disable-oss4
      - --disable-sunaudio
      - --disable-osx_audio
      - --disable-osx_video
      - --disable-aalib
      - --disable-aalibtest
      - --disable-flac
      - --disable-jack
      - --disable-jpeg
      - --disable-libcaca
      - --disable-libdv
      - --disable-libpng
      - --disable-dv1394
      - --disable-shout2
      - --disable-speex
      - --disable-taglib
      - --disable-vpx
      - --disable-wavpack
    build-packages:
      - bison
      - flex
      - libasound2-dev
      - liborc-0.4-dev
      - libpulse-dev
    stage-packages:
      - liborc-0.4-0
      - libpulse0
    after: [gstreamer, gst-plugins-base, libopenh264-library, prepare]
    prime:
      - -usr/lib/gcc
      - -usr/share/doc
      - -usr/share/gtk-doc
    build-attributes: [no-system-libraries]

  gst-plugins-bad:
    plugin: autotools
    source: http://gstreamer.freedesktop.org/src/gst-plugins-bad/gst-plugins-bad-1.10.4.tar.xz
    configflags:
      - --prefix=/usr
      - --disable-rpath
      - --disable-debug
      - --disable-examples
      - --disable-accurip
      - --disable-adpcmdec
      - --disable-adpcmenc
      - --disable-aiff
      - --disable-videoframe_audiolevel
      - --disable-asfmux
      - --disable-audiofxbad
      - --disable-audiomixer
      - --disable-compositor
      - --disable-audiovisualizers
      - --disable-autoconvert
      - --disable-bayer
      - --disable-camerabin2
      - --disable-cdxaparse
      - --disable-coloreffects
      - --disable-dccp
      - --disable-debugutils
      - --disable-dvbsuboverlay
      - --disable-dvdspu
      - --disable-faceoverlay
      - --disable-festival
      - --disable-fieldanalysis
      - --disable-freeverb
      - --disable-frei0r
      - --disable-gaudieffects
      - --disable-geometrictransform
      - --disable-gdp
      - --disable-hdvparse
      - --disable-id3tag
      - --disable-inter
      - --disable-interlace
      - --disable-ivfparse
      - --disable-ivtc
      - --disable-jp2kdecimator
      - --disable-jpegformat
      - --disable-librfb
      - --disable-midi
      - --disable-mve
      - --disable-mxf
      - --disable-netsim
      - --disable-nuvdemux
      - --disable-onvif
      - --disable-patchdetect
      - --disable-pcapparse
      - --disable-pnm
      - --disable-removesilence
      - --disable-sdi
      - --disable-sdp
      - --disable-siren
      - --disable-speed
      - --disable-subenc
      - --disable-stereo
      - --disable-timecode
      - --disable-tta
      - --disable-videofilters
      - --disable-videomeasure
      - --disable-videosignal
      - --disable-vmnc
      - --disable-y4m
      - --disable-yadif
      - --disable-directsound
      - --disable-wasapi
      - --disable-direct3d
      - --disable-winscreencap
      - --disable-winks
      - --disable-android_media
      - --disable-apple_media
      - --disable-bluez
      - --disable-shm
      - --disable-vcd
      - --disable-opensles
      - --disable-uvch264
      - --disable-nvenc
      - --disable-tinyalsa
      - --disable-assrender
      - --disable-voamrwbenc
      - --disable-voaacenc
      - --disable-apexsink
      - --disable-bs2b
      - --disable-bz2
      - --disable-chromaprint
      - --disable-dash
      - --disable-dc1394
      - --disable-decklink
      - --disable-directfb
      - --disable-webp
      - --disable-daala
      - --disable-resindvd
      - --disable-faac
      - --disable-fbdev
      - --disable-fdk_aac
      - --disable-flite
      - --disable-gsm
      - --disable-fluidsynth
      - --disable-kate
      - --disable-kms
      - --disable-ladspa
      - --disable-lv2
      - --disable-libmms
      - --disable-srtp
      - --disable-dtls
      - --disable-linsys
      - --disable-modplug
      - --disable-mimic
      - --disable-mpeg2enc
      - --disable-mplex
      - --disable-musepack
      - --disable-nas
      - --disable-neon
      - --disable-ofa
      - --disable-openal
      - --disable-opencv
      - --disable-openexr
      - --disable-openjpeg
      - --disable-openni2
      - --disable-opus
      - --disable-pvr
      - --disable-rsvg
      - --disable-qt
      - --disable-libvisual
      - --disable-timidity
      - --disable-teletextdec
      - --disable-wildmidi
      - --disable-sndfile
      - --disable-soundtouch
      - --disable-spc
      - --disable-gme
      - --disable-dvb
      - --disable-wininet
      - --disable-acm
      - --disable-sbc
      - --disable-schro
      - --disable-zbar
      - --disable-spandsp
      - --disable-sndio
      - --disable-webrtcdsp
    build-packages:
      - bison
      - flex
      - libasound2-dev
      - libgl1-mesa-dev
      - liborc-0.4-dev
      - libpulse-dev
    stage-packages:
      - liborc-0.4-0
      - libpulse0
    after: [gstreamer, gst-plugins-base, libopenh264-library, prepare]
    prime:
      - -usr/include
      - -usr/lib/gcc
      - -usr/lib/pkgconfig
      - -usr/share/doc
      - -usr/share/gtk-doc
    build-attributes: [no-system-libraries]

  gnome-twitch:
    plugin: meson
    source: https://github.com/vinszent/gnome-twitch/archive/v0.4.1.tar.gz
    prepare: pip3 install meson
    meson-parameters:
      - --buildtype=plain
      - --prefix=/snap/gnome-twitch/current/usr
      - -Ddo-post-install=false
      - -Dbuild-executable=true
      - -Dbuild-player-backends=gstreamer-cairo,gstreamer-opengl
    organize:
      snap/gnome-twitch/current/usr: usr
    build-packages:
      - libjson-glib-dev
      - libpeas-dev
      - libsoup2.4-dev
      - libwebkit2gtk-4.0-dev
      - python3-pip
      - python3-setuptools
    stage-packages:
      - libpeas-1.0-0
    after:
      - desktop-gnome-platform
      - gstreamer
      - gst-plugins-base
      - gst-plugins-good
      - gst-plugins-bad
      - gst-plugins-libav
      - libopenh264-helper
      - prepare
    prime:
      - usr/bin/gnome-twitch
      - usr/lib/**/gnome-twitch
      - usr/lib/**/libgirepository*
      - usr/lib/**/libpeas*
      - usr/share/appdata/*GnomeTwitch*
      - usr/share/applications/*GnomeTwitch*
      - usr/share/glib-2.0/schemas/*GnomeTwitch*
      - usr/share/icons/**/*GnomeTwitch*
      - usr/share/locale/**/gnome-twitch*
    build-attributes: [no-system-libraries]