name: gnome-twitch
version: '0.4.2'
summary: Enjoy Twitch on your GNU/Linux desktop
description: |
  Enjoy Twitch on your GNU/Linux desktop
  
  Easily browse and search channels and games. Keep track of your follows
  whether you have a Twitch account or not.
  A super fast, hardware-accelerated player plus a fully integrated native
  chat makes for a fantastic viewing experience.
  GNOME Twitch is packed with cool features and development is constantly
  on-going, bringing heaps of new stuff straight to you.

grade: stable
confinement: strict
base: core18

architectures:
- build-on: amd64
- build-on: i386

slots:
  dbus-gnome-twitch:
    interface: dbus
    bus: session
    name: com.vinszent.GnomeTwitch

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes:icon-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes:sounds-themes

passthrough:
  layout:
    /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0:
      symlink: $SNAP/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0
    /usr/lib/i386-linux-gnu/webkit2gtk-4.0:
      symlink: $SNAP/usr/lib/i386-linux-gnu/webkit2gtk-4.0
    /usr/lib/x86_64-linux-gnu/alsa-lib:
      symlink: $SNAP/usr/lib/x86_64-linux-gnu/alsa-lib
    /usr/lib/i386-linux-gnu/alsa-lib:
      symlink: $SNAP/usr/lib/i386-linux-gnu/alsa-lib
    /etc/asound.conf:
      symlink: $SNAP/etc/asound.conf
    # /usr/lib/arm-linux-gnueabihf/webkit2gtk-4.0:
    #   symlink: $SNAP/usr/lib/arm-linux-gnueabihf/webkit2gtk-4.0
    # /usr/lib/aarch64-linux-gnu/webkit2gtk-4.0:
    #   symlink: $SNAP/usr/lib/aarch64-linux-gnu/webkit2gtk-4.0
    # /usr/lib/powerpc-linux-gnu/webkit2gtk-4.0:
    #   symlink: $SNAP/usr/lib/powerpc-linux-gnu/webkit2gtk-4.0
    # /usr/lib/s390x-linux-gnu/webkit2gtk-4.0:
    #   symlink: $SNAP/usr/lib/s390x-linux-gnu/webkit2gtk-4.0

apps:
  gnome-twitch:
    command: |
      desktop-launch samba-launch snapcraft-preload $SNAP/usr/bin/gnome-twitch
    desktop: usr/share/applications/com.vinszent.GnomeTwitch.desktop
    plugs:
    - browser-support
    - desktop
    - gsettings
    - network
    - opengl
    - pulseaudio
    - screen-inhibit-control
    - unity7
    - wayland
    - x11

parts:
  desktop-gtk3:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
    - build-essential
    - libgtk-3-dev
    stage-packages:
    - libxkbcommon0  # XKB_CONFIG_ROOT
    - ttf-ubuntu-font-family
    - dmz-cursor-theme
    - light-themes
    - adwaita-icon-theme
    - gnome-themes-standard
    - shared-mime-info
    - libgtk-3-0
    - libgdk-pixbuf2.0-0
    - libglib2.0-bin
    - libgtk-3-bin
    - unity-gtk3-module
    - libappindicator3-1
    - locales-all
    - xdg-user-dirs
    - ibus-gtk3
    - libibus-1.0-5
    - fcitx-frontend-gtk3

  alsa:
    plugin: nil
    source: https://github.com/diddledan/snapcraft-alsa.git
    override-pull: |
      cat > asound.conf <<EOF
      pcm.!default {
        type pulse
        fallback "sysdefault"
        hint {
          show on
          description "Default ALSA Output (currently PulseAudio Sound Server)"
        }
      }
      ctl.!default {
        type pulse
        fallback "sysdefault"
      }
      EOF
    override-build: |
      install -m644 -D -t $SNAPCRAFT_PART_INSTALL/etc asound.conf
    
  samba-launch:
    plugin: nil
    override-pull: |
      cat > samba-launch <<EOF
      #!/bin/bash
      export LD_LIBRARY_PATH="\$SNAP/usr/lib/\$SNAP_LAUNCHER_ARCH_TRIPLET/samba:\$LD_LIBRARY_PATH"
      exec "\$@"
      EOF
    override-build:
      install -m755 -D -t $SNAPCRAFT_PART_INSTALL/bin samba-launch

  snapcraft-preload:
    source: https://github.com/sergiusens/snapcraft-preload.git
    plugin: cmake
    build-packages:
    - gcc-multilib
    - g++-multilib

  gnome-twitch:
    plugin: meson
    source: https://github.com/vinszent/gnome-twitch.git
    source-tag: 'v0.4.2'
    override-pull: |
      pip3 install meson
      snapcraftctl pull
      sed -i 's|^Icon=.*|Icon=${SNAP}/usr/share/icons/hicolor/512x512/apps/com.vinszent.GnomeTwitch.png|'  data/com.vinszent.GnomeTwitch.desktop.in
    meson-parameters:
    - --buildtype=release
    - --prefix=/usr
    - -Dbuild-player-backends=gstreamer-cairo,gstreamer-opengl,gstreamer-clutter,mpv-opengl
    - -Ddo-post-install=false
    build-packages:
    - gettext
    - gobject-introspection
    - libclutter-gst-3.0-dev
    - libclutter-gtk-1.0-dev
    - libdb5.3-dev
    - libglib2.0-dev
    - libglu1-mesa-dev
    - libjson-glib-dev
    - libmpv-dev
    - libpeas-dev
    - libpulse-dev
    - libsoup2.4-dev
    - libwebkit2gtk-4.0-dev
    - python3-pip
    - python3-setuptools
    - python3-wheel
    stage-packages:
    - gstreamer1.0-clutter-3.0
    - gstreamer1.0-gl
    - gstreamer1.0-gtk3
    - gstreamer1.0-libav
    - gstreamer1.0-plugins-base
    - gstreamer1.0-plugins-good
    - gstreamer1.0-plugins-bad
    - libcairo-gobject2
    - libclutter-gst-3.0-0
    - libclutter-gtk-1.0-0
    - libdb5.3
    - libglib2.0-0
    - libglu1-mesa
    - libgpm2
    - libjson-glib-1.0-0
    - libmpv1
    - libpeas-1.0-0
    - libpulse0
    - libslang2
    - libsoup2.4-1
    - libwebkit2gtk-4.0-37
    - samba-libs
    after:
    - desktop-gtk3
